# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_User', '0001_initial'),
        ('_Item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_User.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='_Item.City'),
        ),
        migrations.AddField(
            model_name='distance',
            name='dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='_Item.Item'),
        ),
        migrations.AddField(
            model_name='distance',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src', to='_Item.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='item_tag',
            unique_together=set([('item_id', 'tag_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together=set([('src', 'dst')]),
        ),
    ]
