# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_Item', '0002_auto_20180331_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='city',
        ),
    ]
