# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_Item', '0003_remove_item_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='_Item.City'),
            preserve_default=False,
        ),
    ]
