# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_Item', '0005_auto_20180331_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_minute',
            field=models.IntegerField(default=180),
            preserve_default=False,
        ),
    ]
